apiVersion: v1
kind: Service
metadata:
  name: ramtest-system-entry
  namespace: ramtest
spec:
  type: NodePort
  ports:
  - name: nginx-app
    port: 80
    targetPort: 80
  selector:
    app: ramtest-system-entry