apiVersion: v1
kind: Service
metadata:
  name: ramtest-telemetry
  labels:
    app: ramtest-telemetry
  namespace: ramtest  
spec:
  type: NodePort
  ports:
    - name: vault
      targetPort: 8200
      port: 8200
  selector:
    app: ramtest-telemetry